spring:
  datasource:
    name: duckhyj
    url: jdbc:oracle:thin:@192.168.93.130:1521:duckw
    username: duckw
    password: 387959
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hyj.duckhyj.mapper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
